name: Ping Listener

on:
  repository_dispatch:
    types: [ping]

jobs:
  handle-ping:
    runs-on: ubuntu-latest
    steps:
      - name: Acknowledge ping
        run: |
          echo "🛰️ Ping received: success=${{ github.event.client_payload.success }}"